version: "3.3"

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=${TZ}
    # ports:
    #   - ${PORT}:8123
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    # networks:
    #   - proxy
    # required to connect homekit, HA and homekit devices must be on the same network (wifi router)
    network_mode: host
    volumes:
      # - db_volume:/opt/example/data
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    devices:
      # https://www.home-assistant.io/integrations/zha/#cant-connect-to-usb-device-and-using-docker
      - /dev/ttyUSB0:/dev/ttyUSB0

# networks:
#   proxy:
#     external: true

# volumes:
#   db_volume: